name: "MyPy, Tests, and Linting"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: python3 python3-pip python3-setuptools python3-nose python3-gi python3-xlib python3-dbus gir1.2-glib-2.0 gir1.2-gtk-3.0 gir1.2-wnck-3.0
          version: 1.0
      - uses: actions/setup-python@v5
        with:
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "**/dev_requirements.txt"
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f dev_requirements.txt ]; then pip install -r dev_requirements.txt; fi
      - name: Check types with MyPy
        run: |
          MYPYPATH="quicktile" mypy --config-file=setup.cfg quicktile ./*.py functional_harness
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          python3 -m flake8 --count --exit-zero --max-line-length=127 --config=setup.cfg quicktile/ ./*.py functional_harness
      - name: Test with Nose
        run: |
          nosetests3
